# Generated by Django 5.0.3 on 2024-03-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
    ]
