# Generated by Django 5.0.3 on 2024-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_profile_city_remove_profile_is_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(
                default="Oran", max_length=50, verbose_name="Address"
            ),
        ),
    ]
