# Generated by Django 5.0.3 on 2024-07-02 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ascii", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name_ascii", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name_ascii", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "daira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communes",
                        to="algeria.daira",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="daira",
            name="wilaya",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dairas",
                to="algeria.wilaya",
            ),
        ),
    ]
