# Generated by Django 5.0.3 on 2024-03-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_propertyrequest_remove_property_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_photos")),
            ],
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo1",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo10",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo2",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo3",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo4",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo5",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo6",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo7",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo8",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photo9",
        ),
        migrations.AddField(
            model_name="property",
            name="photos",
            field=models.ManyToManyField(
                related_name="properties", to="properties.photo"
            ),
        ),
    ]
