# Generated by Django 5.0.3 on 2024-07-02 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algeria", "0001_initial"),
        (
            "properties",
            "0004_photo_remove_property_photo1_remove_property_photo10_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Propertysellerinfo",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=150, verbose_name="Email")),
                ("phone", models.CharField(max_length=15, verbose_name="Phone")),
            ],
            options={
                "verbose_name": "Property seller Info",
                "verbose_name_plural": "Property seller Info",
            },
        ),
        migrations.CreateModel(
            name="SavedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Propertyrequest",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="vedio",
            new_name="video",
        ),
        migrations.RemoveField(
            model_name="property",
            name="city",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photos",
        ),
        migrations.AddField(
            model_name="photo",
            name="property",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="properties.property",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.TextField(blank=True, null=True, verbose_name="Amenities"),
        ),
        migrations.AddField(
            model_name="property",
            name="commune",
            field=models.ForeignKey(
                default="1131",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="commune",
                to="algeria.commune",
                verbose_name="Property commune",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="daira",
            field=models.ForeignKey(
                default="374",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="daira",
                to="algeria.daira",
                verbose_name="Property Daira",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="legal_status",
            field=models.CharField(
                default="Clear", max_length=100, verbose_name="Legal Status"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="neighborhood_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Neighborhood Information"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="payment_options",
            field=models.CharField(
                default="Cash", max_length=100, verbose_name="Payment Options"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_status",
            field=models.CharField(
                default="New", max_length=50, verbose_name="Property Status"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="wilaya",
            field=models.ForeignKey(
                default="31",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wilaya",
                to="algeria.wilaya",
                verbose_name="Property Wilaya",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(default=1, verbose_name="Bathrooms"),
        ),
        migrations.AlterField(
            model_name="property",
            name="plot_area",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Plot Area (m^2)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=30, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Appartement", "Appartement"),
                    ("Villa", "Villa"),
                    ("Local", "Local"),
                    ("Terrain", "Terrain"),
                    ("Hangar", "Hangar"),
                    ("Bungalow", "Bungalow"),
                    ("Usine", "Usine"),
                    ("Other", "Other"),
                ],
                default="Appartement",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="agent_buyer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent, Seller or Buyer",
            ),
        ),
        migrations.AddField(
            model_name="propertylike",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.property"
            ),
        ),
        migrations.AddField(
            model_name="propertylike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="propertysellerinfo",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_enquiries",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by_users",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertylike",
            unique_together={("property", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="savedproperty",
            unique_together={("user", "property")},
        ),
    ]
