# Generated by Django 5.0.3 on 2024-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_propertylike_propertysellerinfo_savedproperty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="ascenseur",
            field=models.BooleanField(default=False, verbose_name="Ascenseur"),
        ),
        migrations.AddField(
            model_name="property",
            name="balcon",
            field=models.BooleanField(default=False, verbose_name="Balcon"),
        ),
        migrations.AddField(
            model_name="property",
            name="cave",
            field=models.BooleanField(default=False, verbose_name="Cave"),
        ),
        migrations.AddField(
            model_name="property",
            name="garage",
            field=models.BooleanField(default=False, verbose_name="Garage"),
        ),
        migrations.AddField(
            model_name="property",
            name="gardien",
            field=models.BooleanField(default=False, verbose_name="Gardien"),
        ),
        migrations.AddField(
            model_name="property",
            name="interphone",
            field=models.BooleanField(default=False, verbose_name="Interphone"),
        ),
        migrations.AddField(
            model_name="property",
            name="meuble",
            field=models.BooleanField(default=False, verbose_name="Meublé"),
        ),
        migrations.AddField(
            model_name="property",
            name="parking_exterieur",
            field=models.BooleanField(default=False, verbose_name="Parking Extérieur"),
        ),
        migrations.AddField(
            model_name="property",
            name="parking_sous_sol",
            field=models.BooleanField(default=False, verbose_name="Parking Sous-sol"),
        ),
        migrations.AddField(
            model_name="property",
            name="salle_deau",
            field=models.BooleanField(default=False, verbose_name="Salle d'eau"),
        ),
        migrations.AddField(
            model_name="property",
            name="terrasse",
            field=models.BooleanField(default=False, verbose_name="Terrasse"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Appartement", "Appartement"),
                    ("Villa", "Villa"),
                    ("Local", "Local"),
                    ("Terrain", "Terrain"),
                    ("Hangar", "Hangar"),
                    ("Bungalow", "Bungalow"),
                    ("Usine", "Usine"),
                    ("Bereau", "Bereau"),
                    ("Immeuble", "Immeuble"),
                    ("Other", "Other"),
                ],
                default="Appartement",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
    ]
