# Generated by Django 5.0.3 on 2024-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0006_property_ascenseur_property_balcon_property_cave_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="neighborhood_info",
        ),
        migrations.RemoveField(
            model_name="property",
            name="parking_sous_sol",
        ),
        migrations.RemoveField(
            model_name="property",
            name="payment_options",
        ),
        migrations.AlterField(
            model_name="property",
            name="advert_type",
            field=models.CharField(
                choices=[
                    ("For Sale", "For Sale"),
                    ("For Rent", "For Rent"),
                    ("Echange", "Echange"),
                ],
                default="For Sale",
                max_length=50,
                verbose_name="Advert Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="parking_exterieur",
            field=models.BooleanField(default=False, verbose_name="Parking"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Appartement", "Appartement"),
                    ("Villa", "Villa"),
                    ("Local", "Local"),
                    ("Terrain", "Terrain"),
                    ("Hangar", "Hangar"),
                    ("Bungalow", "Bungalow"),
                    ("Usine", "Usine"),
                    ("Bereau", "Bereau"),
                    ("Immeuble", "Immeuble"),
                    ("Carcas", "Carcas"),
                    ("Terrain Agricole", "Terrain Agricole"),
                    ("Deplux", "Deplux"),
                    ("Studio", "Studio"),
                    ("Other", "Other"),
                ],
                default="Appartement",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="salle_deau",
            field=models.BooleanField(default=False, verbose_name="bage d'eau"),
        ),
    ]
